/**
 * Purpose: Define EXECUTE_ORDER_REQUEST message type for requesting order execution.
 * Exports: ExecuteOrderRequestPayload type, TypeBox schemas.
 * Core Flow: trade-manager publishes → executor-service consumes → executes order via broker adapter.
 */

import { Type, Static } from '@sinclair/typebox';
import { CommandEnum } from './command-enum';

/**
 * TypeBox schema for EXECUTE_ORDER_REQUEST payload validation
 */
export const ExecuteOrderRequestPayloadSchema = Type.Object({
  /**
   * Order ID generated by trade-manager
   * Links this execution request to the Order entity in database
   */
  orderId: Type.String({ minLength: 1 }),

  /**
   * Telegram message ID that triggered this order
   */
  messageId: Type.Integer({ minimum: 1 }),
  /**
   * Telegram channel ID where the message originated
   */
  channelId: Type.String({ minLength: 1 }),
  /**
   * Account ID for order execution
   */
  accountId: Type.String({ minLength: 1 }),
  /**
   * Trace token for tracking this order across services
   */
  traceToken: Type.String({ minLength: 1 }),
  /**
   * Trading symbol
   */
  symbol: Type.String({ minLength: 1 }),
  /**
   * Command type (LONG, SHORT, MOVE_SL, SET_TP_SL, CLOSE_PARTIAL, etc.)
   */
  command: Type.Enum(CommandEnum),
  /**
   * Position size in lots/contracts (optional)
   * - For LONG/SHORT: if > 0, executor uses the provided value directly. If omitted or 0: executor calculates based on account config (risk %, default lot size)
   * - For CLOSE_PARTIAL: represents the reduction amount in lots/contracts
   */
  lotSize: Type.Optional(Type.Number({ minimum: 0 })),
  /**
   * Whether to execute immediately (market order) or wait for limit price
   * @default false (limit order)
   */
  isImmediate: Type.Optional(Type.Boolean()),
  /**
   * Entry price (optional)
   * - For market orders (isImmediate=true): can be omitted
   * - For limit orders (isImmediate=false): required
   */
  entry: Type.Optional(Type.Number({ minimum: 0 })),
  /**
   * Stop loss configuration (optional)
   * Can specify either price or pips, or both
   */
  stopLoss: Type.Optional(
    Type.Object({
      /**
       * Exact stop loss price
       */
      price: Type.Optional(Type.Number({ minimum: 0 })),
      /**
       * Stop loss in pips from entry
       */
      pips: Type.Optional(Type.Number()),
    })
  ),
  /**
   * Take profit targets (optional)
   * Supports multiple TP levels
   * Each TP can specify either price or pips, or both
   */
  takeProfits: Type.Optional(
    Type.Array(
      Type.Object({
        /**
         * Exact take profit price
         */
        price: Type.Optional(Type.Number({ minimum: 0 })),
        /**
         * Take profit in pips from entry
         */
        pips: Type.Optional(Type.Number()),
      })
    )
  ),
  /**
   * Leverage multiplier (optional, for futures)
   */
  leverage: Type.Optional(Type.Number({ minimum: 1 })),
  /**
   * Meta information from AI translation (optional)
   * Only available for LONG and SHORT commands
   * Used by executor-service to adjust execution behavior
   */
  meta: Type.Optional(
    Type.Object({
      /**
       * Whether to reduce lot size for this order
       * When true, executor-service should reduce the calculated lot size
       * Only available for LONG and SHORT commands
       */
      reduceLotSize: Type.Optional(Type.Boolean()),
      /**
       * Whether to adjust entry/stop loss for this order
       * When true, executor-service should adjust the stop loss using
       * the addOnStopLossPercentForAdjustEntry from account config
       * Only available for LONG and SHORT commands
       */
      adjustEntry: Type.Optional(Type.Boolean()),
      /**
       * Internal execution instructions
       * Separates technical control flags from AI-derived logic
       */
      executionInstructions: Type.Optional(
        Type.Object({
          /**
           * Whether to skip linked order TP/SL synchronization
           * When true, prevents the auto-sync job from triggering additional
           * sync operations on linked orders, breaking potential recursion loops
           */
          skipLinkedOrderSync: Type.Optional(Type.Boolean()),
          /**
           * Whether to skip broker price adjustment for stop loss
           * When true, prevents re-adjusting already adjusted SL values
           */
          skipBrokerPriceAdjustment: Type.Optional(Type.Boolean()),
          /**
           * Override the take profit tiers persisted in the database
           * Used by auto-sync jobs to preserve the original tier list
           */
          takeProfitTiers: Type.Optional(
            Type.Array(
              Type.Object({
                price: Type.Number({ minimum: 0 }),
                isUsed: Type.Optional(Type.Boolean()),
              })
            )
          ),
        })
      ),
    })
  ),
  /**
   * Order creation timestamp
   */
  timestamp: Type.Integer({ minimum: 1 }),
});

/**
 * Payload type for EXECUTE_ORDER_REQUEST
 */
export type ExecuteOrderRequestPayload = Static<
  typeof ExecuteOrderRequestPayloadSchema
>;
